### ISSUE TITLE
Buttons jump when example command text is deleted

### ISSUE THREAD

**Issue by FloatingMilkshake** [SapphireVideos/dotsimus-webpage-idea#1]
When the example command text is deleted, the Discord and GitHub buttons jump...but only sometimes. Screen recording [here](https://streamable.com/11xv8h) (uploaded to Streamable because it was too big for GitHub).

**Comment by SapphireVideos** [comment]
Thank you very much. I did a change in the system for preventing it and feels fixed.

**Comment by SapphireVideos** [comment]
I made it always jump instead of never...

**Comment by SapphireVideos** [comment]
Now is actually fixed, sorry for the incovenience.
